[theme]
base                     = "light"
primaryColor             = "#e53935"
backgroundColor          = "#f0faf9"
secondaryBackgroundColor = "#ffffff"
textColor                = "#1a1a2e"
font                     = "sans serif"

[server]
maxUploadSize            = 50
headless                 = true

[browser]
gatherUsageStats         = false
