import io
import datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak,
)
from reportlab.graphics.shapes import Drawing, String as GString
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics import renderPDF

from config.settings import APP_NAME, SEVERITY_COLORS


_SEV_COLORS_RL = {
    "CRITICAL": colors.HexColor("#dc3545"),
    "HIGH": colors.HexColor("#fd7e14"),
    "MEDIUM": colors.HexColor("#ffc107"),
    "LOW": colors.HexColor("#28a745"),
    "INFO": colors.HexColor("#17a2b8"),
}


def generate_pdf_report(
    findings: list[dict],
    username: str,
    email: str,
    analyzed_files: list[str],
    append_mode: bool = False,
    generated_at: Optional[datetime.datetime] = None,
) -> bytes:
    if generated_at is None:
        generated_at = datetime.datetime.utcnow()

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    story = []

    # ── Title ─────────────────────────────────────────────────────────────────
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"], fontSize=18, textColor=colors.HexColor("#003366"), spaceAfter=6
    )
    story.append(Paragraph(APP_NAME, title_style))
    story.append(Paragraph("Security Analysis Report", ParagraphStyle("Sub", parent=styles["Normal"], fontSize=13, textColor=colors.grey)))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#003366"), spaceAfter=10))

    # ── Report metadata ────────────────────────────────────────────────────────
    meta_data = [
        ["Generated By:", f"{username} ({email})"],
        ["Analysis Date:", generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["Append Mode:", "ENABLED" if append_mode else "DISABLED"],
        ["Rules Applied:", "Administrator-approved rule set (Static + Dynamic)"],
        ["Files Analyzed:", "\n".join(analyzed_files) if analyzed_files else "N/A"],
    ]
    meta_table = Table(meta_data, colWidths=[4.5 * cm, 13 * cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#f0f0f0"), colors.white]),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Executive Summary ──────────────────────────────────────────────────────
    story.append(Paragraph("Executive Summary", ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#003366"))))

    from services.threat_engine import compute_summary
    summary = compute_summary(findings)

    summary_data = [
        ["Total Threats", "Critical", "High", "Medium", "Low"],
        [str(summary["total"]), str(summary["CRITICAL"]), str(summary["HIGH"]), str(summary["MEDIUM"]), str(summary["LOW"])],
    ]
    sum_table = Table(summary_data, colWidths=[3.5 * cm] * 5)
    sum_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#003366")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BACKGROUND", (1, 1), (1, 1), _SEV_COLORS_RL.get("CRITICAL", colors.red)),
        ("BACKGROUND", (2, 1), (2, 1), _SEV_COLORS_RL.get("HIGH", colors.orange)),
        ("BACKGROUND", (3, 1), (3, 1), _SEV_COLORS_RL.get("MEDIUM", colors.yellow)),
        ("BACKGROUND", (4, 1), (4, 1), _SEV_COLORS_RL.get("LOW", colors.green)),
        ("TEXTCOLOR", (1, 1), (4, 1), colors.white),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(sum_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Severity pie chart ─────────────────────────────────────────────────────
    pie_data = [summary[s] for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW") if summary[s] > 0]
    pie_labels = [s for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW") if summary[s] > 0]
    pie_colors = [_SEV_COLORS_RL[s] for s in pie_labels]

    if pie_data:
        d = Drawing(350, 160)
        pie = Pie()
        pie.x = 30
        pie.y = 10
        pie.width = 130
        pie.height = 130
        pie.data = pie_data
        pie.labels = pie_labels
        pie.simpleLabels = 0
        for i, c in enumerate(pie_colors):
            pie.slices[i].fillColor = c
            pie.slices[i].strokeColor = colors.white
        # Legend
        for i, (label, c) in enumerate(zip(pie_labels, pie_colors)):
            d.add(GString(180, 130 - i * 20, f"  {label}: {pie_data[i]}", fontSize=9, fillColor=c))
        d.add(pie)
        story.append(d)
        story.append(Spacer(1, 0.3 * cm))

    # ── Threat Findings Table ─────────────────────────────────────────────────
    if findings:
        story.append(Paragraph("Detailed Threat Findings", ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#003366"))))

        table_data = [["#", "Severity", "Rule", "Timestamp", "Source IP", "Description"]]
        for i, f in enumerate(findings[:500], 1):
            _ts = f.get("timestamp")
            try:
                import pandas as _pd
                ts_str = _ts.strftime("%Y-%m-%d %H:%M") if (_ts is not None and not _pd.isnull(_ts)) else "N/A"
            except (TypeError, ValueError, AttributeError):
                ts_str = str(_ts)[:16] if _ts is not None else "N/A"
            table_data.append([
                str(i),
                f.get("severity", ""),
                Paragraph(f.get("rule_name", "")[:40], styles["Normal"]),
                ts_str,
                f.get("source_ip") or "N/A",
                Paragraph(f.get("description", "")[:120], styles["Normal"]),
            ])

        findings_table = Table(
            table_data,
            colWidths=[0.8 * cm, 2 * cm, 3.5 * cm, 3 * cm, 2.2 * cm, 5.5 * cm],
            repeatRows=1,
        )
        ts = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#003366")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7.5),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.lightgrey),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
        ]
        # Color-code severity column
        sev_col_bg = {"CRITICAL": colors.HexColor("#f8d7da"), "HIGH": colors.HexColor("#ffeeba"),
                      "MEDIUM": colors.HexColor("#fff3cd"), "LOW": colors.HexColor("#d4edda")}
        for row_i, f in enumerate(findings[:500], 1):
            bg = sev_col_bg.get(f.get("severity", ""), colors.white)
            ts.append(("BACKGROUND", (1, row_i), (1, row_i), bg))
        findings_table.setStyle(TableStyle(ts))
        story.append(findings_table)

    # ── Footer note ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7, textColor=colors.grey)
    story.append(Paragraph(
        "NOTE: This report is NOT stored on the server. Please save a copy for your records. "
        f"Generated by {APP_NAME} on {generated_at.strftime('%Y-%m-%d %H:%M:%S')} UTC.",
        footer_style,
    ))

    doc.build(story)
    return buffer.getvalue()


def get_report_filename(analyzed_files: list[str]) -> str:
    date_str = datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    return f"security_report_{date_str}.pdf"
