import io
import html
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether,
)

from config.settings import APP_NAME, now_ist
from services.recommendations import get_recommendations, get_general_actions


_SEV_COLORS_RL = {
    "CRITICAL": colors.HexColor("#dc3545"),
    "HIGH":     colors.HexColor("#fd7e14"),
    "MEDIUM":   colors.HexColor("#ffc107"),
    "LOW":      colors.HexColor("#28a745"),
    "INFO":     colors.HexColor("#17a2b8"),
}


def _esc(text) -> str:
    """Escape &, <, > so ReportLab's mini-XML paragraph parser treats text literally."""
    return html.escape(str(text or ""), quote=False)


# Severity left-accent-bar colours (match the Rules page left-edge palette).
_SEV_BAR = {
    "CRITICAL": colors.HexColor("#ef4444"), "HIGH": colors.HexColor("#f97316"),
    "MEDIUM": colors.HexColor("#f59e0b"), "LOW": colors.HexColor("#22c55e"),
    "INFO": colors.HexColor("#38bdf8"),
}
# Readable label text colours for severity / action headings.
_SEV_TEXT = {
    "CRITICAL": "#c81e2c", "HIGH": "#c2410c", "MEDIUM": "#b45309",
    "LOW": "#15803d", "INFO": "#0369a1",
}


def generate_pdf_report(
    findings: list[dict],
    username: str,
    email: str,
    analyzed_files: list[str],
    generated_at=None,
    application: str = "",
    leanix_id: str = "",
) -> bytes:
    if generated_at is None:
        generated_at = now_ist()

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    story = []

    navy   = colors.HexColor("#003366")
    teal   = colors.HexColor("#00838f")
    dark   = colors.HexColor("#1a202c")

    title_style = ParagraphStyle("Title",  parent=styles["Title"],   fontSize=18, textColor=navy, spaceAfter=6)
    h2_style    = ParagraphStyle("H2",     parent=styles["Heading2"], textColor=navy)
    h3_style    = ParagraphStyle("H3",     parent=styles["Heading3"], textColor=teal, fontSize=11)
    body_style  = ParagraphStyle("Body",   parent=styles["Normal"],   fontSize=9, leading=13)
    bullet_style = ParagraphStyle("Bullet", parent=styles["Normal"],  fontSize=9, leading=13,
                                  leftIndent=14, bulletIndent=4)
    small_style = ParagraphStyle("Small",  parent=styles["Normal"],   fontSize=7, textColor=colors.grey)

    # ── Title ─────────────────────────────────────────────────────────────────
    story.append(Paragraph(APP_NAME, title_style))
    story.append(Paragraph(
        "Security Analysis Report",
        ParagraphStyle("Sub", parent=styles["Normal"], fontSize=13, textColor=colors.grey),
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=navy, spaceAfter=10))

    # ── Report metadata ────────────────────────────────────────────────────────
    # Application/Product + LeanIX/PIF ID (and the "Rules Applied" note) appear only for
    # IT Owner reports, which always carry that context. Admin test reports have neither.
    has_context = bool(application or leanix_id)
    meta_data = []
    if has_context:
        meta_data.append(["Application/Product:", application or "N/A"])
        meta_data.append(["LeanIX ID / PIF ID:", leanix_id or "N/A"])
    meta_data.append(["Generated By:", f"{username} ({email})"])
    meta_data.append(["Analysis Date:", f"{generated_at.strftime('%d-%m-%Y %H:%M:%S')} IST"])
    if has_context:
        meta_data.append(["Rules Applied:", "Administrator-approved rule set (Static + Behavioral)"])
    meta_data.append(["Files Analyzed:", "\n".join(analyzed_files) if analyzed_files else "N/A"])
    meta_table = Table(meta_data, colWidths=[4.5 * cm, 13 * cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME",       (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",       (0, 0), (-1, -1), 9),
        ("VALIGN",         (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#f0f0f0"), colors.white]),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 4),
        ("TOPPADDING",     (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Executive Summary ──────────────────────────────────────────────────────
    story.append(Paragraph("Executive Summary", h2_style))

    from services.threat_engine import compute_summary
    summary = compute_summary(findings)

    summary_data = [
        ["Total Threats", "Critical", "High", "Medium", "Low"],
        [str(summary["total"]), str(summary["CRITICAL"]), str(summary["HIGH"]),
         str(summary["MEDIUM"]), str(summary["LOW"])],
    ]
    sum_table = Table(summary_data, colWidths=[3.5 * cm] * 5)
    sum_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), navy),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("FONTSIZE",      (0, 0), (-1, -1), 10),
        ("BACKGROUND",    (1, 1), (1, 1), _SEV_COLORS_RL["CRITICAL"]),
        ("BACKGROUND",    (2, 1), (2, 1), _SEV_COLORS_RL["HIGH"]),
        ("BACKGROUND",    (3, 1), (3, 1), _SEV_COLORS_RL["MEDIUM"]),
        ("BACKGROUND",    (4, 1), (4, 1), _SEV_COLORS_RL["LOW"]),
        ("TEXTCOLOR",     (1, 1), (4, 1), colors.white),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(sum_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Detected threat types table (full list, most frequent first) ────────────
    if findings:
        story.append(Paragraph("Detected Threat Types", h2_style))
        from collections import Counter
        rule_counts = Counter(f["rule_name"] for f in findings)
        top_rules = rule_counts.most_common()  # all detected rule types, not just top N

        top_data = [["#", "Threat Rule", "Count", "Severity"]]
        for i, (rname, cnt) in enumerate(top_rules, 1):
            sev = next((f["severity"] for f in findings if f["rule_name"] == rname), "")
            top_data.append([str(i), rname, str(cnt), sev])

        top_table = Table(top_data, colWidths=[0.8*cm, 9*cm, 2*cm, 2.5*cm])
        top_ts = [
            ("BACKGROUND",    (0, 0), (-1, 0), navy),
            ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ALIGN",         (0, 0), (-1, -1), "LEFT"),
            ("ALIGN",         (2, 0), (2, -1), "CENTER"),
            ("GRID",          (0, 0), (-1, -1), 0.3, colors.lightgrey),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ]
        sev_bg = {"CRITICAL": colors.HexColor("#f8d7da"), "HIGH": colors.HexColor("#ffeeba"),
                  "MEDIUM": colors.HexColor("#fff3cd"), "LOW": colors.HexColor("#d4edda")}
        for row_i, (rname, _) in enumerate(top_rules, 1):
            sev = next((f["severity"] for f in findings if f["rule_name"] == rname), "")
            bg = sev_bg.get(sev, colors.white)
            top_ts.append(("BACKGROUND", (3, row_i), (3, row_i), bg))
        top_table.setStyle(TableStyle(top_ts))
        story.append(top_table)
        story.append(Spacer(1, 0.4 * cm))

    # ── Recommended Actions ─────────────────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("Recommended Actions", h2_style))
    story.append(HRFlowable(width="100%", thickness=1.2, color=teal, spaceBefore=1, spaceAfter=7))
    story.append(Paragraph(
        "The following remediation steps are recommended based on the threats detected in this analysis.",
        body_style,
    ))
    story.append(Spacer(1, 0.32 * cm))

    # Card geometry (A4 usable width ≈ 17 cm = 21 cm − 2×2 cm margins).
    BAR_W, CONTENT_W, HDR_W = 0.16 * cm, 16.74 * cm, 15.8 * cm
    card_border = colors.HexColor("#e5e7eb")

    name_style   = ParagraphStyle("RecName", parent=styles["Normal"], fontSize=10.5,
                                   textColor=navy, leading=13)
    meta_style   = ParagraphStyle("RecMeta", parent=styles["Normal"], fontSize=8.5,
                                   leading=11, alignment=2)  # 2 = right-aligned
    issue_style  = ParagraphStyle("RecIssue", parent=styles["Normal"], fontSize=8.6,
                                   leading=12.5, textColor=colors.HexColor("#5b6573"))
    action_style = ParagraphStyle("RecAction", parent=styles["Normal"], fontSize=8.6,
                                   leading=12.5, textColor=colors.HexColor("#1a202c"))

    def _accent_card(inner_flowables, sev):
        """Wrap content flowables in a white card with a coloured severity left bar."""
        card = Table([["", inner_flowables]], colWidths=[BAR_W, CONTENT_W])
        card.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (0, 0), _SEV_BAR.get(sev, colors.grey)),
            ("BACKGROUND",    (1, 0), (1, 0), colors.white),
            ("BOX",           (0, 0), (-1, -1), 0.6, card_border),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING",   (0, 0), (0, 0), 0), ("RIGHTPADDING", (0, 0), (0, 0), 0),
            ("TOPPADDING",    (0, 0), (0, 0), 0), ("BOTTOMPADDING", (0, 0), (0, 0), 0),
            ("LEFTPADDING",   (1, 0), (1, 0), 11), ("RIGHTPADDING", (1, 0), (1, 0), 11),
            ("TOPPADDING",    (1, 0), (1, 0), 8),  ("BOTTOMPADDING", (1, 0), (1, 0), 8),
        ]))
        return card

    # Immediate Response: one highlighted callout for the highest severity present.
    general = get_general_actions(summary)
    rec_num = 0  # numbering for the per-rule cards only (Immediate Response stays unnumbered)
    if general:
        highest = next((s for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW") if summary.get(s, 0) > 0), "")
        txt = _SEV_TEXT.get(highest, "#444444")
        inner = [Paragraph(
            f'<b><font color="{txt}" size="11">Immediate Response</font></b>'
            f'&nbsp;&nbsp;<font color="#9aa0a6" size="8">— {_esc(highest)} severity detected</font>',
            ParagraphStyle("IRHead", parent=styles["Normal"], spaceAfter=5),
        )]
        for action in general:
            inner.append(Paragraph(
                f'<font color="{txt}"><b>•</b></font>&nbsp;&nbsp;{_esc(action)}',
                ParagraphStyle("IRItem", parent=styles["Normal"], fontSize=8.8, leading=13.5,
                               leftIndent=4, spaceAfter=1.5),
            ))
        # Immediate Response: a full alert-coloured border (no left accent bar).
        ir_card = Table([[inner]], colWidths=[BAR_W + CONTENT_W])
        ir_card.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, -1), colors.white),
            ("BOX",          (0, 0), (-1, -1), 1.5, colors.grey),
            ("ROUNDEDCORNERS", [4, 4, 4, 4]),  # smooth ~4px corners
            ("VALIGN",       (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING",  (0, 0), (-1, -1), 12), ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING",   (0, 0), (-1, -1), 9),  ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
        ]))
        story.append(KeepTogether(ir_card))
        story.append(Spacer(1, 0.38 * cm))

    # Per-rule recommendation cards: rule header + Issue + Action.
    recs = get_recommendations(findings)
    for rec in recs:
        rec_num += 1
        sev = rec["severity"]
        txt = _SEV_TEXT.get(sev, "#444444")

        meta_html = f'<b><font color="{txt}">{_esc(sev)}</font></b>'
        header = Table(
            [[Paragraph(f"{rec_num}. " + _esc(rec["rule_name"]), name_style), Paragraph(meta_html, meta_style)]],
            colWidths=[HDR_W * 0.64, HDR_W * 0.36],
        )
        header.setStyle(TableStyle([
            ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING",  (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING",   (0, 0), (-1, -1), 0), ("BOTTOMPADDING", (0, 0), (-1, 0), 5),
            ("LINEBELOW",    (0, 0), (-1, 0), 0.5, colors.HexColor("#eef1f4")),
        ]))

        inner = [header]
        if rec.get("issue"):
            inner.append(Spacer(1, 4))
            inner.append(Paragraph(
                f'<b><font color="#374151">Issue:</font></b>&nbsp; {_esc(rec["issue"])}', issue_style))
        if rec.get("action"):
            inner.append(Spacer(1, 3))
            inner.append(Paragraph(
                f'<b><font color="{txt}">Action:</font></b>&nbsp; {_esc(rec["action"])}', action_style))

        story.append(KeepTogether(_accent_card(inner, sev)))
        story.append(Spacer(1, 0.22 * cm))

    # ── Footer ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph(
        f"NOTE: This report is NOT stored on the server. Please save a copy for your records. "
        f"Generated by {APP_NAME} on {generated_at.strftime('%d-%m-%Y %H:%M:%S')} IST.",
        small_style,
    ))

    doc.build(story)
    return buffer.getvalue()


def get_report_filename(analyzed_files: list[str]) -> str:
    ts = now_ist().strftime("%Y%m%d_%H%M%S")
    return f"security_report_{ts}.pdf"
