import io
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak,
)

from config.settings import APP_NAME, now_ist
from services.recommendations import get_recommendations, get_general_actions


_SEV_COLORS_RL = {
    "CRITICAL": colors.HexColor("#dc3545"),
    "HIGH":     colors.HexColor("#fd7e14"),
    "MEDIUM":   colors.HexColor("#ffc107"),
    "LOW":      colors.HexColor("#28a745"),
    "INFO":     colors.HexColor("#17a2b8"),
}


def generate_pdf_report(
    findings: list[dict],
    username: str,
    email: str,
    analyzed_files: list[str],
    append_mode: bool = False,
    generated_at=None,
) -> bytes:
    if generated_at is None:
        generated_at = now_ist()

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    story = []

    navy   = colors.HexColor("#003366")
    teal   = colors.HexColor("#00838f")
    dark   = colors.HexColor("#1a202c")

    title_style = ParagraphStyle("Title",  parent=styles["Title"],   fontSize=18, textColor=navy, spaceAfter=6)
    h2_style    = ParagraphStyle("H2",     parent=styles["Heading2"], textColor=navy)
    h3_style    = ParagraphStyle("H3",     parent=styles["Heading3"], textColor=teal, fontSize=11)
    body_style  = ParagraphStyle("Body",   parent=styles["Normal"],   fontSize=9, leading=13)
    bullet_style = ParagraphStyle("Bullet", parent=styles["Normal"],  fontSize=9, leading=13,
                                  leftIndent=14, bulletIndent=4)
    small_style = ParagraphStyle("Small",  parent=styles["Normal"],   fontSize=7, textColor=colors.grey)

    # ── Title ─────────────────────────────────────────────────────────────────
    story.append(Paragraph(APP_NAME, title_style))
    story.append(Paragraph(
        "Security Analysis Report",
        ParagraphStyle("Sub", parent=styles["Normal"], fontSize=13, textColor=colors.grey),
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=navy, spaceAfter=10))

    # ── Report metadata ────────────────────────────────────────────────────────
    meta_data = [
        ["Generated By:",  f"{username} ({email})"],
        ["Analysis Date:", f"{generated_at.strftime('%Y-%m-%d %H:%M:%S')} IST"],
        ["Append Mode:",   "ENABLED" if append_mode else "DISABLED"],
        ["Rules Applied:", "Administrator-approved rule set (Static + Dynamic)"],
        ["Files Analyzed:", "\n".join(analyzed_files) if analyzed_files else "N/A"],
    ]
    meta_table = Table(meta_data, colWidths=[4.5 * cm, 13 * cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME",       (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",       (0, 0), (-1, -1), 9),
        ("VALIGN",         (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#f0f0f0"), colors.white]),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 4),
        ("TOPPADDING",     (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Executive Summary ──────────────────────────────────────────────────────
    story.append(Paragraph("Executive Summary", h2_style))

    from services.threat_engine import compute_summary
    summary = compute_summary(findings)

    summary_data = [
        ["Total Threats", "Critical", "High", "Medium", "Low"],
        [str(summary["total"]), str(summary["CRITICAL"]), str(summary["HIGH"]),
         str(summary["MEDIUM"]), str(summary["LOW"])],
    ]
    sum_table = Table(summary_data, colWidths=[3.5 * cm] * 5)
    sum_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), navy),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("FONTSIZE",      (0, 0), (-1, -1), 10),
        ("BACKGROUND",    (1, 1), (1, 1), _SEV_COLORS_RL["CRITICAL"]),
        ("BACKGROUND",    (2, 1), (2, 1), _SEV_COLORS_RL["HIGH"]),
        ("BACKGROUND",    (3, 1), (3, 1), _SEV_COLORS_RL["MEDIUM"]),
        ("BACKGROUND",    (4, 1), (4, 1), _SEV_COLORS_RL["LOW"]),
        ("TEXTCOLOR",     (1, 1), (4, 1), colors.white),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(sum_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Top threat types table ─────────────────────────────────────────────────
    if findings:
        story.append(Paragraph("Top Detected Threat Types", h2_style))
        from collections import Counter
        rule_counts = Counter(f["rule_name"] for f in findings)
        top_rules = rule_counts.most_common(15)

        top_data = [["#", "Threat Rule", "Count", "Severity"]]
        for i, (rname, cnt) in enumerate(top_rules, 1):
            sev = next((f["severity"] for f in findings if f["rule_name"] == rname), "")
            top_data.append([str(i), rname, str(cnt), sev])

        top_table = Table(top_data, colWidths=[0.8*cm, 9*cm, 2*cm, 2.5*cm])
        top_ts = [
            ("BACKGROUND",    (0, 0), (-1, 0), navy),
            ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ALIGN",         (0, 0), (-1, -1), "LEFT"),
            ("ALIGN",         (2, 0), (2, -1), "CENTER"),
            ("GRID",          (0, 0), (-1, -1), 0.3, colors.lightgrey),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ]
        sev_bg = {"CRITICAL": colors.HexColor("#f8d7da"), "HIGH": colors.HexColor("#ffeeba"),
                  "MEDIUM": colors.HexColor("#fff3cd"), "LOW": colors.HexColor("#d4edda")}
        for row_i, (rname, _) in enumerate(top_rules, 1):
            sev = next((f["severity"] for f in findings if f["rule_name"] == rname), "")
            bg = sev_bg.get(sev, colors.white)
            top_ts.append(("BACKGROUND", (3, row_i), (3, row_i), bg))
        top_table.setStyle(TableStyle(top_ts))
        story.append(top_table)
        story.append(Spacer(1, 0.4 * cm))

    # ── Recommended Actions (continues right after the threat types table) ─────
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("Recommended Actions", h2_style))
    story.append(Paragraph(
        "The following remediation steps are recommended based on the threats detected in this analysis.",
        body_style,
    ))
    story.append(Spacer(1, 0.3 * cm))

    # General severity-level guidance
    general = get_general_actions(summary)
    if general:
        highest = next((s for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW") if summary.get(s, 0) > 0), "")
        story.append(Paragraph(f"Immediate Response ({highest} severity detected)", h3_style))
        for action in general:
            story.append(Paragraph(f"• {action}", bullet_style))
        story.append(Spacer(1, 0.3 * cm))

    # Per-rule recommendations
    recs = get_recommendations(findings)
    sev_bg_light = {
        "CRITICAL": colors.HexColor("#fff0f0"),
        "HIGH":     colors.HexColor("#fff8f0"),
        "MEDIUM":   colors.HexColor("#fffef0"),
        "LOW":      colors.HexColor("#f0fff8"),
    }

    for rec in recs:
        rule_name = rec["rule_name"]
        severity  = rec["severity"]
        bg = sev_bg_light.get(severity, colors.HexColor("#f9f9f9"))

        header_data = [[
            Paragraph(f"<b>{rule_name}</b>", ParagraphStyle("RH", parent=styles["Normal"], fontSize=10)),
            Paragraph(f"<b>{severity}</b>", ParagraphStyle("RS", parent=styles["Normal"], fontSize=9,
                      textColor=_SEV_COLORS_RL.get(severity, colors.grey))),
            Paragraph(f"Urgency: {rec.get('urgency','')}", small_style),
        ]]
        hdr_table = Table(header_data, colWidths=[9*cm, 2*cm, 4*cm])
        hdr_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), bg),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("BOX",           (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ]))
        story.append(hdr_table)

        # Why / Impact
        story.append(Paragraph(
            f"<i>Why suspicious:</i> {rec.get('why', '')}",
            ParagraphStyle("Why", parent=styles["Normal"], fontSize=8, leading=11,
                           leftIndent=10, textColor=colors.HexColor("#555555")),
        ))

        # Action steps
        for action in rec.get("actions", []):
            story.append(Paragraph(f"→  {action}", ParagraphStyle(
                "Act", parent=styles["Normal"], fontSize=8.5, leading=12,
                leftIndent=18, bulletIndent=8,
            )))
        story.append(Spacer(1, 0.25 * cm))

    # ── Footer ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph(
        f"NOTE: This report is NOT stored on the server. Please save a copy for your records. "
        f"Generated by {APP_NAME} on {generated_at.strftime('%Y-%m-%d %H:%M:%S')} IST.",
        small_style,
    ))

    doc.build(story)
    return buffer.getvalue()


def get_report_filename(analyzed_files: list[str]) -> str:
    ts = now_ist().strftime("%Y%m%d_%H%M%S")
    return f"security_report_{ts}.pdf"
